apiVersion: v1
kind: ConfigMap
metadata:
  name: matomo-config
  namespace: matomo
data:
  MATOMO_DATABASE_HOST: matomo-db-svc
  MATOMO_DATABASE_DBNAME: proddb
  config.ini.php: |
    enable_installer = 0
