apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-app
  namespace: matomo
spec:
  selector:
    matchLabels:
      app: matomo-app
  template:
    metadata:
      labels:
        app: matomo-app
    spec:
      volumes:
      - name: matomoconfig
        configMap:
          name: matomo-phpini-config
          items:
            - key: config.ini.php
              path: /var/www/html/config/config.ini.php
      containers:
        - name: matomo-app
          image: matomo:4.13.1
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
          - containerPort: 80
            protocol: TCP
          envFrom:
          - configMapRef:
              name: matomo-config
          env:
          - name: MATOMO_DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: matomodbsecret
                key: MARIADB_USER
                optional: false
          - name: MATOMO_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: matomodbsecret
                key: MARIADB_PASSWORD
                optional: false
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo-db
  namespace: matomo
spec:
  selector:
    matchLabels:
      app: matomo-db
  template:
    metadata:
      labels:
        app: matomo-db
    spec:
      volumes:
      - name: matomodb-volume
        persistentVolumeClaim:
          claimName: matomodb-pvc
      containers:
        - name: matomo-db
          image: mariadb:10.9.4
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
          - containerPort: 3306
            protocol: TCP
          envFrom:
          - secretRef:
              name: matomodbsecret
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: matomodb-volume
          args:
            - "--max-allowed-packet=67108864"