apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomodb-pvc
  namespace: matomo
spec:
  storageClassName: matomo-sc
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }