kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: matomo-sc
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /data/matomo
volumeBindingMode: WaitForFirstConsumer
